/**
 * `types/supabase.ts` (generated by `npm run db:types` from the actual Postgres schema — see
 * supabase/migrations/) is the ONE authoritative source for database shapes. Nothing here
 * redefines a table's columns by hand; these are thin generic helpers derived from it, so a
 * future schema change only ever requires regenerating that one file, never hunting down a
 * second hand-maintained copy.
 *
 * Usage:
 *   import type { Tables, TablesInsert, TablesUpdate, Enums } from "@/lib/supabase/types";
 *   type FashionRequestRow = Tables<"fashion_requests">;
 *   type NewProposal = TablesInsert<"proposals">;
 *
 * Note: `types/index.ts` (the existing hand-written frontend types — Customer, Designer,
 * FashionRequest, etc.) is a SEPARATE, deliberately untouched type system for this phase — the
 * frontend still runs on lib/store.ts's in-memory mock data and reads those types, not these.
 * The two are not meant to conflict: this file is for new backend-foundation code only, until a
 * later integration phase reconciles them.
 */

import type { Database } from "@/types/supabase";

export type { Database };

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T];

export type Views<T extends keyof Database["public"]["Views"]> =
  Database["public"]["Views"][T]["Row"];
